// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
       google()
       mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}


apply plugin: 'com.android.application'


android {
    namespace 'org.amarplayer.amarplayer'
    compileSdkVersion 36
    buildToolsVersion '37.0.0'
    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 10241
        versionName '0.1'
        manifestPlaceholders = [:]
    }

	
	packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        doNotStrip '**/*.so'
        
	}
	

	

    

    buildTypes {
        debug {
        }
        release {
            
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            jniLibs.srcDir 'libs'
            java {}
        }
    }

    aaptOptions {
        noCompress "tflite"
    }

}

dependencies {
    implementation files('src/main/libs/Qt6AndroidBindings.jar')
    implementation files('src/main/libs/Qt6AndroidMultimedia.jar')
    implementation files('src/main/libs/Qt6Android.jar')
    
}
